pipeline {
    agent any 
    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t selvavignesh02/alpine:latest .'
            }
        }
        stage('Run Docker Container') {
            steps {
                sh 'docker run -d selvavignesh02/alpine:latest'
            }
        }
        stage('Push to Docker Registry') {
            steps {
                sh 'docker push selvavignesh02/alpine:latest'
            }
        }
    }
}


