pipeline {
    agent any 

    stages {

        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image
                    sh 'docker build -t my-app-image -f docker-test/Dockerfile .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Run the Docker container
                    sh 'docker run -d -p 8080:8080 --name my-running-app my-app-image'
                }
            }
        }
    }

    post {
        success {
            echo "Docker container is running successfully."
        }
        failure {
            echo "Build or Run failed."
        }
    }
}


